### ISSUE TITLE
Learn how Flask works

### ISSUE THREAD

**Issue by Tiiglo** [EECE3093C/team-project-dylan-frontend#5]
This is just something for us to play around with once we get a simple website up and running. I just want to be able to mess around with buttons on the website while attached to a simple backend code to see how it will function.

**Comment by PerryJohnsonUC** [comment]
With my most recent commit, I added a folder called "test_flask" which provides a basic example of how flask works and communicates with the HTML file.

**Comment by PerryJohnsonUC** [comment]
Discussed at meeting on 3/29 -- we are getting more comfortable with using flask.
