### ISSUE TITLE
Incorporate class structure within flask with multiple jobs

### ISSUE THREAD

**Issue by PerryJohnsonUC** [EECE3093C/team-project-dylan-frontend#9]
We have classes in backend code to deal with multiple calculators. Add functionality to HTML page that asks the user how many jobs they had, then add information for that many jobs and compute a basic calculation.

**Comment by bsabo17** [comment]
I think the current structure will work as long as all the Flask functions can run in each class and sub-class function as needed

**Comment by PerryJohnsonUC** [comment]
Had to change up the structure a little bit to account for flask functions in the classes, latest push has the final structure
